### ISSUE TITLE
Header Area

### ISSUE THREAD

**Issue by yildiraykoyuncu** [Eltayeb-Elgaali/duck-duck-clone#1]
__As a site visitor, I want to see a menu and social media icons on the top; so I can find my way through the site and reach social media accounts of duck-duck-go easily__

### Repo

- [x] developed on a branch named `Header Area`

### HTML

- [x] Add header section.
- [x] Add icons for navigation menu and social media accounts menu.
- [x] Add a div containing menu items.
- [x] Add a div containing social media icons.

### CSS

- [x] Add layout styling for header and icons.
- [x] Add layout styling for the navigation menu.
- [x] Add styling for menu items.
- [x] Add layout styling for the social media accounts menu.
- [x] Add styling for social media accounts menu icons.
- [x] Add effect to both menus for smooth opening and closing.

### JS
 
- [x] Add functionality to menu icons.

**Comment by yaredyilma** [comment]
This is brilliant!! everything works. I don't know how you did the menu so cleanly. good job in such a short time.
